---
abstract: 'make warnings FATAL at compile-time only'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.96
  Test::Warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 1
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.014, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: warnings-MaybeFatal
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  warnings::MaybeFatal:
    file: lib/warnings/MaybeFatal.pm
    version: 0.002
requires:
  B::Hooks::EndOfScope: 0
  perl: 5.008001
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/warnings-MaybeFatal/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=warnings-MaybeFatal
  homepage: https://metacpan.org/release/warnings-MaybeFatal
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-warnings-maybefatal
version: 0.002
